name: "Build"
on:
  - workflow_dispatch
jobs:
  test:
    uses: ./.github/workflows/main.yml
    with:
      mode: '["build"]'
      alphas: '["qwerty"]'
      nav: '["default"]'
      clipboard: '["mac"]'
      layers: '["default"]'
      mapping: '["lite"]'
      kmonad_os: '["mac"]'
